name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHANGESETS_TOKEN  }}

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN  }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
